/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.Jugador;
import civitas.TituloPropiedad;
import java.util.ArrayList;
/**
 *
 * @author Usuario
 */
public class JugadorPanel extends javax.swing.JPanel {

    private Jugador jugador;
    /**
     * Creates new form JuegadorPanel
     */
    public JugadorPanel() {
        initComponents();
        this.propiedades.setPreferredSize(new java.awt.Dimension(350,320));
    }

    public void setJugador(Jugador otro){
        this.jugador = otro;

      
        if (this.jugador.getEncarcelado())
            this.encarcelado.setText("SI");
        else
            this.encarcelado.setText("NO");
        
        if(this.jugador.isEpeculador())
            this.especulador.setText("SI");
        else
            this.especulador.setText("NO");
        
        
        this.saldo.setText( "" + this.jugador.getSaldo());
        
        this.nombre.setText(this.jugador.getNombre());
        
        
        this.repaint();
        
        this.rellenaPropiedades(this.jugador.getPropiedades());
        
    }
    
    private void rellenaPropiedades (ArrayList<TituloPropiedad> lista) {
    // Se elimina la información antigua
    propiedades.removeAll();
    this.listaPropiedades.removeAll();
    // Se recorre la lista de propiedades para ir creando sus vistas individuales y
   //añadirlas al panel
    for (TituloPropiedad t : lista) {
        //PropiedadPanel vistaPropiedad = new PropiedadPanel();
       // vistaPropiedad.setPropiedad(t);

        //propiedades.add(vistaPropiedad);
        //vistaPropiedad.setVisible(true);
        
        this.listaPropiedades.add(t.getNombre());
    }
    // Se fuerza la actualización visual del panel propiedades y del panel del jugador
    repaint();
    revalidate();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lSaldo = new javax.swing.JLabel();
        lEncarcelado = new javax.swing.JLabel();
        lNombre = new javax.swing.JLabel();
        lEspeculador = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        saldo = new javax.swing.JTextField();
        encarcelado = new javax.swing.JTextField();
        especulador = new javax.swing.JTextField();
        propiedades = new javax.swing.JPanel();
        listaPropiedades = new java.awt.List();

        lSaldo.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        lSaldo.setText("Saldo");
        lSaldo.setEnabled(false);

        lEncarcelado.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        lEncarcelado.setText("Encarcelado");
        lEncarcelado.setEnabled(false);

        lNombre.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        lNombre.setText("Nombre");
        lNombre.setEnabled(false);

        lEspeculador.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        lEspeculador.setText("Especulador");
        lEspeculador.setEnabled(false);

        nombre.setEnabled(false);
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        saldo.setEnabled(false);

        encarcelado.setEnabled(false);

        especulador.setEnabled(false);

        propiedades.setAutoscrolls(true);

        listaPropiedades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaPropiedadesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lSaldo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lNombre)
                                    .addGap(32, 32, 32)))
                            .addComponent(lEncarcelado)
                            .addComponent(lEspeculador))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(saldo)
                            .addComponent(encarcelado)
                            .addComponent(especulador)))
                    .addComponent(listaPropiedades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(propiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lNombre)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lSaldo)
                            .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lEncarcelado)
                            .addComponent(encarcelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lEspeculador)
                            .addComponent(especulador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaPropiedades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(propiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void listaPropiedadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPropiedadesMouseClicked
        // TODO add your handling code here:
        propiedades.removeAll();
        
        String t = this.listaPropiedades.getSelectedItem();
        TituloPropiedad titulo  = null;
        if(t != null || t != "")
            titulo = this.jugador.getTitulo(t);
        
        if(titulo != null){
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(titulo);

            propiedades.add(vistaPropiedad);
            vistaPropiedad.setVisible(true); 
        }
        
        repaint();
        revalidate();

        
    }//GEN-LAST:event_listaPropiedadesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField encarcelado;
    private javax.swing.JTextField especulador;
    private javax.swing.JLabel lEncarcelado;
    private javax.swing.JLabel lEspeculador;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lSaldo;
    private java.awt.List listaPropiedades;
    private javax.swing.JTextField nombre;
    private javax.swing.JPanel propiedades;
    private javax.swing.JTextField saldo;
    // End of variables declaration//GEN-END:variables
}
