/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.TituloPropiedad;
/**
 *
 * @author Usuario
 */
public class PropiedadPanel extends javax.swing.JPanel {

    private TituloPropiedad tituloPropiedad;
    
    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }

    public void setPropiedad(TituloPropiedad otro){
        this.tituloPropiedad = otro;
        
        this.nombre.setText(otro.getNombre());

        this.edificar.setText(""+otro.getPrecioEdificar());
        this.Casas.setText(""+otro.getNumCasas());
        this.hoteles.setText(""+otro.getNumHoteles());
        
        if (otro.getHipotecado())
            this.hipotecada.setText("SI");
        else
            this.hipotecada.setText("NO");
        
        this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNombre = new javax.swing.JLabel();
        jEdificar = new javax.swing.JLabel();
        jCasas = new javax.swing.JLabel();
        jHoteles = new javax.swing.JLabel();
        jHipotecada = new javax.swing.JLabel();
        nombre = new java.awt.TextField();
        edificar = new java.awt.TextField();
        Casas = new java.awt.TextField();
        hoteles = new java.awt.TextField();
        hipotecada = new java.awt.TextField();

        jNombre.setText("Nombre");
        jNombre.setEnabled(false);

        jEdificar.setText("Precio Edificar");
        jEdificar.setEnabled(false);

        jCasas.setText("Casas");
        jCasas.setEnabled(false);

        jHoteles.setText("Hoteles");
        jHoteles.setEnabled(false);

        jHipotecada.setText("Hipotecada");
        jHipotecada.setEnabled(false);

        nombre.setEnabled(false);
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        edificar.setEnabled(false);
        edificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edificarActionPerformed(evt);
            }
        });

        Casas.setEnabled(false);
        Casas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasasActionPerformed(evt);
            }
        });

        hoteles.setEnabled(false);
        hoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelesActionPerformed(evt);
            }
        });

        hipotecada.setEnabled(false);
        hipotecada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hipotecadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCasas)
                                .addComponent(jHoteles)
                                .addComponent(jHipotecada))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Casas, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hoteles, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hipotecada, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jEdificar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(edificar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jNombre)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jEdificar)
                    .addComponent(edificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCasas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Casas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jHoteles)
                        .addGap(18, 18, 18)
                        .addComponent(jHipotecada))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hipotecada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void hipotecadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hipotecadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hipotecadaActionPerformed

    private void edificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edificarActionPerformed

    private void hotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotelesActionPerformed

    private void CasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField Casas;
    private java.awt.TextField edificar;
    private java.awt.TextField hipotecada;
    private java.awt.TextField hoteles;
    private javax.swing.JLabel jCasas;
    private javax.swing.JLabel jEdificar;
    private javax.swing.JLabel jHipotecada;
    private javax.swing.JLabel jHoteles;
    private javax.swing.JLabel jNombre;
    private java.awt.TextField nombre;
    // End of variables declaration//GEN-END:variables
}
